//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WorkItem
    {
        public int Id { get; set; }
        [Required]
        [MinLength(50)]
        public string Title { get; set; }
        [Required]
        [MinLength(30)]
        public string Status { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime CreatedDate { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime CompletedDate { get; set; }
    }
}
